name: Setup Node

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: pnpm
        cache-dependency-path: "pnpm-lock.yaml"
    - run: npm run setup
      shell: bash
    - run: pnpm i
      shell: bash
